### ISSUE TITLE
example has errors

### ISSUE THREAD

**Issue by thought7878** [MariaMelnik/flutter_date_pickers#10]
example has errors

> Target of URI doesn't exist: 'package:flutter_date_picker/color_selector_btn.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

![git](https://user-images.githubusercontent.com/5996844/70125757-6bfdb400-16b2-11ea-96c4-e69b599676c5.png)

**Comment by MariaMelnik** [comment]
@thought7878 you need to do "flutter packages get" from example's folder to get all dependencies. After it example should work.
I am closing this. Feel free to open again in case of any problems here.
