### ISSUE TITLE
cannot find maybeOf

### ISSUE THREAD

**Issue by mostafasaadamin** [MariaMelnik/flutter_date_pickers#107]
/E:/flutter_windows_3.3.2/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_date_pickers-0.4.2/lib/src/icon_btn.dart:34:33: Error: Member not found: 'Material.maybeOf'.
    bool isMaterial =  Material.maybeOf(context) != null;

**Comment by MariaMelnik** [comment]
@mostafasaadamin try to use 0.4.1 version or upgrade flutter.
