### ISSUE TITLE
Listener when sliding DayPicker

### ISSUE THREAD

**Issue by sergiomalluelef** [MariaMelnik/flutter_date_pickers#12]
How to hear the slip between months in DatePicker?

**Comment by MariaMelnik** [comment]
@sergiomalluelef currently main purpose of this widget is select some dates. So callback for changing month is not provided yet. 
What is your case? If it is look like common case I can add it to the new release.

**Comment by TatsuUkraine** [comment]
this feature will be quite useful. For instance - as I understood calendar can't be infinite, at least start and end dates are required. With this listener, developer can update start/end date based on currently selected month like startDate = selectedMonth - 1, endDate = selectedMonth + 1. and make date picker basically infinite

**Comment by MariaMelnik** [comment]
@TatsuUkraine you are right calendar can't be infinite but you can set lastDate and firstDate as you wish like first date 01.01.1900 and end date like 01.01.2200. It will give feeling of the inifine calendar.

But you option is valid as well. Might be I will added in future releases.

**Comment by MariaMelnik** [comment]
@TatsuUkraine @sergiomalluelef in new **0.1.7** version every day based pickers (day, week and range pickers) have `onMonthChange` callback. You can use it to listen month changes and handle it according to your logic.

I am closing issue. Don't hesitate to reopen it if you will find any bugs.
