### ISSUE TITLE
!_debugLocked: is not true

### ISSUE THREAD

**Issue by Popovma** [MariaMelnik/flutter_date_pickers#13]
When using Navigator.pop in the onChanged method to close the calendar widget, the following error is thrown:

'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2330 pos 12: '!_debugLocked': is not true.

If I pick a day in the same month that the calendar is created, I do not get an error. The error only appears if I go backwards or forwards a month and select a date.  I also get the error when I move forward (or backward) a month and then come back to the month that the calendar was created in.  For example, if I use today's date as the selected date, the month is January.  If I use the arrows and go back to December or forward to February and select a date, I get the above error.

**Comment by MariaMelnik** [comment]
@Popovma thank you for reporting.
Could you provide minimum running example?
It is important what is your navigation stack before you do Navigator.pop. If you have only one route in this stack and you do Navigator.pop from this route it might cause the problem.

**Comment by Popovma** [comment]
Hi Maria,

I was able to duplicate the problem by using it in the simple flutter demo project.  I have copied the code below.  

Thank you for your help!

import 'package:flutter/material.dart';
import 'package:flutter_date_pickers/flutter_date_pickers.dart' as dp;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String date;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    date = DateTime.now().toIso8601String();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Selected Date:',
            ),
            Text(
              '$date',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _openDatePicker(context);
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }

  void _openDatePicker(BuildContext context) {
    showModalBottomSheet<DateTime>(
        context: context,
        builder: (BuildContext context) {
          return Container(
            child: dp.DayPicker(
              selectedDate: DateTime.now(),
              onChanged: (dateTime) {
                Navigator.pop(context, dateTime);
              },
              firstDate: DateTime.now().subtract(Duration(days: 360)),
              lastDate: DateTime.now().add(Duration(days: 360)),
            ),
          );
        }).then(
      (dateTime) {
        if (dateTime != null) {
          setState(() {
            date = dateTime.toIso8601String();
          });
          print('date time: ' + date);
        } else {
          print('No Day Selected');
        }
      },
    );
  }
}

**Comment by MariaMelnik** [comment]
@Popovma it is general issue, not related with date pickers. You can use any button instead date picker and get same message.

Reason is: you are trying to call Navigator.pop (close date picker) while other Navigator.pop (close bottom sheet) might not finished yet.

More info and fixes you can find in this [stackoverflow question](https://stackoverflow.com/questions/55618717/error-thrown-on-navigator-pop-until-debuglocked-is-not-true).

Hope it helps!
