### ISSUE TITLE
Can't select end date on other week

### ISSUE THREAD

**Issue by fgrenot** [MariaMelnik/flutter_date_pickers#21]
Hello,

on the new version (0.1.0), I  can't select an end date on an other week.
Exemple:
I select 02/15/2020 for first date and when I want to select 06/22/2020 for last date I can't.

**Comment by MariaMelnik** [comment]
@fgrenot could you post code what you used to create date picker?

If you use RangePicker and there is any disable date between first date and last date - range won't be selected. You will have UnselectablePeriodException with disabled dates in range you try to select.

**Comment by fgrenot** [comment]
Yes, I use RangePicker with disable date on the week-end and public holidays.
Can I block the UnsekectablePeriodException ? Because with the version 0.0.6 I haven't this problem.

**Comment by MariaMelnik** [comment]
@fgrenot 0.0.6 has [issue](Range picker allows picking date ranges between disabled dates #15). It is fixed now so there is no ability to select range/week with disabled dates.

How would you like this to work? Might be I will add more customization here in future.

**Comment by MariaMelnik** [comment]
@fgrenot now (from version 0.1.7) ```UnselectablePeriodError``` contains information about period which can not be selected. You can use this information to change seletected day/range with setState (or some state management solution if you use any).

Don't hesitate to reopen this issue or create new if issue will occurred.
