### ISSUE TITLE
Cannot select any date.

### ISSUE THREAD

**Issue by droidzone** [MariaMelnik/flutter_date_pickers#22]
import 'package:flutter/material.dart';
    import 'package:flutter_date_pickers/flutter_date_pickers.dart' as pickerlib;
    
    Future<void> _showMyDialog() async {
        return showDialog<void>(
        context: context,
        barrierDismissible: false, // user must tap button!
        builder: (BuildContext context) {
            return AlertDialog(
            title: Text('Select a Date'),
            content: pickerlib.DayPicker(
                firstDate: DateTime(todaysDate.year - 5),
                lastDate: DateTime(todaysDate.year + 5),
                selectedDate: chosen_date,
                onChanged: (newDate) {
                chosen_date = newDate;
                formatted_date = formatDate(newDate);
                },
            ),
            actions: <Widget>[
                FlatButton(
                child: Text('Select'),
                onPressed: () {
                    Navigator.of(context).pop();
                },
                ),
            ],
            );
        },
        );
    }

    RaisedButton(
        color: Colors.white,
        onPressed: () {
        _showMyDialog();
        },
        child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
            Text(
            'Selected Date',
            style: TextStyle(color: Colors.blue),
            ),
            Text(
            formatted_date,
            style: TextStyle(color: Colors.blue),
            ),
            RaisedButton(
            color: Colors.blue,
            onPressed: () {
                var now = DateTime.now();
                setState(() {
                chosen_date =
                    new DateTime(now.year, now.month, now.day);
                formatted_date = formatDate(chosen_date);
                print("In Today, chosen_date:$chosen_date");
                });
            },
            child: Text(
                'Today',
            ),
            ),
        ],
        ),
    ),

I'm unable to select any date. The dialog pops up, but on clicking any date, nothing happens.

**Comment by MariaMelnik** [comment]
@droidzone pickers don't handle selection itself. You need to set selectedDate/selectedPeriod to picker outside to change it.

You have onChanged where you handle selection but it doesn't change any state inside picker. You should keep selectionDate somewhere outside picker and use setState or another option to change picker's state.

You can look at the examples to get idea how it can be done in simple case.
