### ISSUE TITLE
Calendar prevents ListView from scrolling

### ISSUE THREAD

**Issue by ArchannaDevi88** [MariaMelnik/flutter_date_pickers#23]
Even though the calendar is horizontally scrollable and not vertical. The problem with this is, inside a ListView, it will prevent the ListView from vertical scrolling, so I need to scroll outside the Calendar to scroll the ListView instead of the Calendar.If i try to scroll by holding calendar it gets struck.

**Comment by MariaMelnik** [comment]
@ArchannaDevi88 to 0.1.1 added scrollPhysics property to the DatePickerLayoutSettings.
So you can set it to NeverScrollableScrollPhysics() and it will prevent date pickers to scroll.

Change you dependency to 
```
dependencies:
  flutter_date_pickers: ^0.1.1
```

**Comment by ArchannaDevi88** [comment]
@MariaMelnik , Thank you so much .. its working fine with latest release..
