### ISSUE TITLE
Dates are missing

### ISSUE THREAD

**Issue by ollydixon** [MariaMelnik/flutter_date_pickers#24]
No July the 31st 1992

<img width="281" alt="Screenshot 2020-06-21 at 12 41 58" src="https://user-images.githubusercontent.com/6940726/85222591-ad3e8280-b3bc-11ea-8c24-09317e0cc8c8.png">

**Comment by MariaMelnik** [comment]
@ollydixon it is definitely not a picker from flutter_date_pickers package.

If you will use pickers from this package everything will be correct.
<img width="356" alt="Screenshot 2020-06-21 at 15 50 55" src="https://user-images.githubusercontent.com/20188655/85225055-221eb600-b3d7-11ea-86ed-f22e5f699824.png">

**Comment by ollydixon** [comment]
@MariaMelnik sorry! My bad, never done that before embarrassing :-D

**Comment by MariaMelnik** [comment]
@ollydixon no problem :)
