### ISSUE TITLE
set the first day of week

### ISSUE THREAD

**Issue by SogoGolf** [MariaMelnik/flutter_date_pickers#25]
hi there, is it possible to set the first day of the week ? for example we need to set the first day as Saturday. appreciate if you can let me know.

**Comment by MariaMelnik** [comment]
@SogoGolf hi,
for now first day of the week is related with locale. So in USA it will be Sunday, in Russia it will be Monday.

Could you describe use case where you need custom first day of the week?

**Comment by SogoGolf** [comment]
in the app golfers compete in weekly competitions that start on a Saturday and end on Friday. That is why we need Saturday as the first day of each week in the date grid.

**Comment by MariaMelnik** [comment]
@SogoGolf use new version 0.1.4. I added ```int firstDayOfWeekIndex``` to DatePickerStyles class. Set 6 if you need to set first day as Saturday.

<img width="370" alt="Screenshot 2020-07-02 at 19 29 20" src="https://user-images.githubusercontent.com/20188655/86386610-ae17c400-bc9a-11ea-9139-b1e937603932.png">

I am closing this issue. Don't hesitate to reopen it if you have questions about this property.

**Comment by SogoGolf** [comment]
brilliant many thanks. we'll look to integrate this into our app will let you know if any questions along the way. thanks again.
