### ISSUE TITLE
RangePicker now showing when button pressed

### ISSUE THREAD

**Issue by heshesh2010** [MariaMelnik/flutter_date_pickers#26]
Container(
                      height: 40,
                      width: MediaQuery.of(context).size.width - 250,
                      child: FlatButton(
                        child: Text(
                          S.of(context).booking,
                          style: TextStyle(color: Theme.of(context).hintColor),
                        ),
                        color: Theme.of(context).accentColor,
                        onPressed: () {
                          // add some colors to default settings
                          DatePickerRangeStyles styles = DatePickerRangeStyles(
                            selectedPeriodLastDecoration: BoxDecoration(
                                color: Colors.red,
                                borderRadius: BorderRadius.only(
                                    topRight: Radius.circular(10.0),
                                    bottomRight: Radius.circular(10.0))),
                            selectedPeriodStartDecoration: BoxDecoration(
                              color: Colors.green,
                              borderRadius: BorderRadius.only(
                                  topLeft: Radius.circular(10.0),
                                  bottomLeft: Radius.circular(10.0)),
                            ),
                            selectedPeriodMiddleDecoration: BoxDecoration(
                                color: Colors.yellow,
                                shape: BoxShape.rectangle),
                          );

                          RangePicker(
                                  selectedPeriod: con.selectedPeriod,
                                  onChanged: con.onSelectedDateChanged,
                                  firstDate: DateTime.now()
                                      .subtract(Duration(days: 45)),
                                  lastDate:
                                      DateTime.now().add(Duration(days: 45)),
                                  datePickerStyles: styles

                                  );
                           
                        },
                      ),
                    ),

**Comment by MariaMelnik** [comment]
@heshesh2010 onPressed for FlatButton is a callback. It means this function will be called when user taps on that FlatButton.
So when user taps on your FlatButton ```styles`` will be created. And after it ```RangePicker``` constructor will be called. But created RangePicker is not used in future.

If you would like to show dialog (for example) you can use [showDialog](https://api.flutter.dev/flutter/material/showDialog.html) where you can pass created ```RangePicker``` (you should initialize some variable before. Now there is no any variable to store picker you create in callback) to ```builder``` property.

It is one way, there are another as well. It depends what exactly you would like to do.

I am closing it because it is not issue of library.
