### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by carlosrjr** [MariaMelnik/flutter_date_pickers#42]
Hey! 
Can you create any implementation for this feature? that's possible?
 
![image](https://user-images.githubusercontent.com/15968341/95094075-dda5f480-06ff-11eb-8789-4cde11211119.png)

**Comment by xlamn** [comment]
you can take a look at this package: https://github.com/dylanwuzh/flutter-cupertino-date-picker

**Comment by MariaMelnik** [comment]
@carlosrjr as @xlamn said you can check [packages](https://pub.dev/) which provide cupertino picker.
