### ISSUE TITLE
Select time change date

### ISSUE THREAD

**Issue by xlamn** [MariaMelnik/flutter_date_pickers#44]
Hi,

In Europe we have time changes (one in october, one in march). If I want to select the 28th of march in the RangePicker, it will automatically generate a Period between the 28th and the 29th of march because the endPeriod is 2021-03-29 00:59.59.999. Can you please fix this? My timezone is (GMT +2).

**Comment by MariaMelnik** [comment]
@xlamn thanks for the report. Will check and fix asap.

**Comment by MariaMelnik** [comment]
@xlamn could you provide simple example?
I just checked with Finland locale which is GMT + 2 and wasn't able to reproduce it.
<img width="389" alt="Screenshot 2020-10-25 at 11 51 37" src="https://user-images.githubusercontent.com/20188655/97102689-ac926180-16b8-11eb-9bcf-7b842425894e.png">

**Comment by xlamn** [comment]
> 
> 
> @xlamn could you provide simple example?
> I just checked with Finland locale which is GMT + 2 and wasn't able to reproduce it.
> <img alt="Screenshot 2020-10-25 at 11 51 37" width="389" src="https://user-images.githubusercontent.com/20188655/97102689-ac926180-16b8-11eb-9bcf-7b842425894e.png">

Sure. I think because yesterday was the day where the time change happened it wasn't that ideal to reproduce the problem. Maybe that's why you couldn't produce it. The problem now appears in the GMT+1 time zone for me.

![Screenshot_20201026-091403](https://user-images.githubusercontent.com/32935491/97148722-e5d7d980-176b-11eb-87f7-4de43be00acc.png)
![Screenshot_20201026-091423](https://user-images.githubusercontent.com/32935491/97148724-e7090680-176b-11eb-8ec6-cf187643a75b.png)

**Comment by MariaMelnik** [comment]
@xlamn please check 0.1.8 version. It should be fixed there.
![photo5240064133997637729](https://user-images.githubusercontent.com/20188655/97161815-5a703f80-178f-11eb-8fee-508fc99fca6f.jpg)
![photo5240064133997637730](https://user-images.githubusercontent.com/20188655/97161930-85f32a00-178f-11eb-949a-676a1f36736b.jpg)

**Comment by xlamn** [comment]
jup, thanks for the quick reaction!
