### ISSUE TITLE
Stop automatic month change on day deselection

### ISSUE THREAD

**Issue by fida1989** [MariaMelnik/flutter_date_pickers#48]
Hello, 
I am facing issue while deselecting dates in `DayPicker.multi(..)` widget. When there is only 1 selected date in current month view if I deselect that date current calendar view automatically shifts to next or previous month view. How to disable this behavior? Any kind of suggestions will be highly appreciated.   

**Scenario:**
<img src="https://user-images.githubusercontent.com/2511367/102004477-572f1400-3d3b-11eb-8a87-a6687e3e59be.gif" width="400" height="800">

**Comment by MariaMelnik** [comment]
@fida1989 could you provide code sample?

Also you can check example for multi picker in examples folder days_picker_page.dart? Are you be able to reproduce same error with this example?

**Comment by fida1989** [comment]
Following is the code snippet being used:

![Screenshot at 2020-12-13 20-11-33](https://user-images.githubusercontent.com/2511367/102014323-836c8400-3d7f-11eb-8976-3c0a3da28ff1.png)

Haven't yet checked the examples. Will take a look.

**Comment by fida1989** [comment]
I temporarily solved the issue by creating a `bool` variable in `DayBasedChangeablePickerPresenter` which disables automatic month changes after 1st build.
