### ISSUE TITLE
[RangePicker] Link between Circular BoxShape Start/End period and MiddlePeriod

### ISSUE THREAD

**Issue by HubnerJonathan** [MariaMelnik/flutter_date_pickers#49]
First of all amazing package !

I'm encoutering a small problem with the BoxDecoration of the RangePicker. If I use a circular BoxShape for the selectedPeriod(Start/End)Decoration the background of the container keep it's white color leaving me with an ugly space between the selectedPeriod(Start/End) and the middlePeriod decoration. 

I'd like to fill half of the container background with the same color as the middlePeriod to make it better looking.

Here is what I have because an image is worth a thousand words :
![image](https://user-images.githubusercontent.com/2485966/102015958-ba7e6d80-3d5e-11eb-962e-d0da7fc6267c.png)

And here is what I want : 
![image](https://user-images.githubusercontent.com/2485966/102016068-3973a600-3d5f-11eb-8fab-b499d902d745.png)

**Comment by MariaMelnik** [comment]
@HubnerJonathan thanks for using package!

Currently only way you can customize boxes itself (not text inside it) is using BoxDecoration. So doing something like on the picture is not so simple. I can suggest next way: 

1. Add circle image of the target color to the assets. In this case it will be orange circle with transparent background. Like this:
<img width="100" alt="bg" src="https://user-images.githubusercontent.com/20188655/102020452-67baab00-3d8a-11eb-8c10-5824995fa49e.png">

2. Don't forget to add this image as asset in pubspec.yaml. For example if you name it```bg.png``` and it is in ```images``` folder of the project:

```
# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/bg.png
```
3. Create DatePickerRangeStyles using circle image from assets like this:
```
    Color middleBgColor = Color.fromRGBO(237, 237, 250, 1);
    DecorationImage circleImg = DecorationImage(
          image: AssetImage('images/bg.png'),
          fit: BoxFit.contain
    );

    // add selected colors to default settings
    DatePickerRangeStyles styles = DatePickerRangeStyles(
      selectedPeriodLastDecoration: BoxDecoration(
          color: middleBgColor,
          gradient: LinearGradient(
              colors: [middleBgColor, Colors.transparent],
              stops: [0.5, 0.5]
          ),
          image: circleImg, 
          borderRadius: const BorderRadius.only(
              topRight: Radius.circular(24.0),
              bottomRight: Radius.circular(24.0))
      ),
      selectedPeriodStartDecoration: BoxDecoration(
        color: middleBgColor,
        gradient: LinearGradient(
            colors: [Colors.transparent, middleBgColor,],
            stops: [0.5, 0.5]
        ),
        image: circleImg,
        borderRadius: const BorderRadius.only(
            topLeft: Radius.circular(24.0),
            bottomLeft: Radius.circular(24.0)
        ),
      ),
      selectedPeriodMiddleDecoration: BoxDecoration(
          color: middleBgColor, 
          shape: BoxShape.rectangle
      ),
    );
```

4. Use it in the RangePicker like this:
```
 RangePicker(
           ...
            datePickerStyles: styles,
           ...
          ),
```

Result is: 
<img width="342" alt="Screenshot 2020-12-13 at 21 19 06" src="https://user-images.githubusercontent.com/20188655/102020413-1e6a5b80-3d8a-11eb-9598-ab6bed379876.png">

**Comment by HubnerJonathan** [comment]
This is a super smart work around !
I'm gonna work on that a bit later and keep you posted.

Thanks a lot :) !

**Comment by HubnerJonathan** [comment]
@MariaMelnik It's working thx !

**Comment by MariaMelnik** [comment]
@HubnerJonathan great news!
I am closing this issue. Don't hesitate to reopen it you will need to.
