### ISSUE TITLE
How to remove the bottom space from range picker?

### ISSUE THREAD

**Issue by MungaraJay** [MariaMelnik/flutter_date_pickers#50]
I'm using following code to set date range picker in flutter. But, How can I remove range picker bottom margin.

```
RangePicker(
                  selectedPeriod: _selectedPeriod,
                  onChanged: _onSelectedDateChanged,
                  firstDate: _firstDate,
                  lastDate: _lastDate,
                  datePickerStyles: styles,
                  eventDecorationBuilder: _eventDecorationBuilder,
                  // selectableDayPredicate: _isSelectableCustom,
                  onSelectionError: _onSelectionError,
                )
```

Thanks

**Comment by MariaMelnik** [comment]
@MungaraJay 
If you can provide a picture it will help.

I can assume you have something like this:
<img width="388" alt="Screenshot 2021-02-19 at 17 32 51" src="https://user-images.githubusercontent.com/20188655/108517493-8bddbf80-72d8-11eb-8009-f00544db80b1.png">

and want to have something like this:
<img width="390" alt="Screenshot 2021-02-19 at 17 32 35" src="https://user-images.githubusercontent.com/20188655/108517521-939d6400-72d8-11eb-8233-d03db362c114.png">

This behaviour is customisable. You can do:
```
RangePicker(
            datePickerLayoutSettings: DatePickerLayoutSettings(
              maxDayPickerRowCount: 5
            ),
           ...
        ),
```

But this padding on the bottom is not actually a padding. It is row for days.
Some months you will only need 5 rows but another months 6. And if you set ```maxDayPickerRowCount: 5``` when you have 6-rows month last row will be skipped.

If you want to change this behaviour dynamically you can do it using ```RangePicker.onMonthChanged``` callback. So when user changes month you should manually calculate how many rows it takes and set exactly this value to ```DatePickerLayoutSettings.maxDayPickerRowCount```.

**Comment by MariaMelnik** [comment]
@MungaraJay I am closing this issue due to no answer. Don't hesitate to reopen it if you would like to continue.
