### ISSUE TITLE
Flutter 2.0 Support

### ISSUE THREAD

**Issue by ollydixon** [MariaMelnik/flutter_date_pickers#52]
You need to update the library, the flutter guys forgot to use deprecated flag on some fields.

"date_picker.dart:103:34: Error: No named parameter with the name 'shadowThemeOnly'."

**Comment by MariaMelnik** [comment]
@ollydixon thank you for the opening this issue. I am currently doing this. Hope will be done this weekend.

**Comment by MariaMelnik** [comment]
@ollydixon you can use 0.2.0 version now:
```flutter_date_pickers: ^0.2.0```
