### ISSUE TITLE
Internationalization to pt-BR failure

### ISSUE THREAD

**Issue by GiovannyLucas** [MariaMelnik/flutter_date_pickers#54]
When I use the language **pt** (portuguese) in my app, the **internationalization** joins the preposition "de" (like "of", in english), with month name. Thus, it seems that the month has a strange name, like "dejan" ("ofjun", example in english).

The example to understand follows below:

The month names in english, correctly without preposition:
![image](https://user-images.githubusercontent.com/41789184/111362489-9c7e1d00-866d-11eb-8999-f6001428086b.png)

The month names in portuguese, with a preposition next to the name:
![image](https://user-images.githubusercontent.com/41789184/111361868-edd9dc80-866c-11eb-9350-f038e06b8e09.png)

What can I do to solve it?

**Comment by MariaMelnik** [comment]
@GiovannyLucas thank you for posting issue.
It is fixed for 0.2.1 version
You can use it:
```
dependencies:
  flutter_date_pickers: ^0.2.1
```

**Comment by GiovannyLucas** [comment]
Wow! Perfect.

Thank you so much, I checked and all is right!
