### ISSUE TITLE
Missing month in RangePicker

### ISSUE THREAD

**Issue by metajet98** [MariaMelnik/flutter_date_pickers#56]
- Flutter 1.22.5
- flutter_date_pickers: 0.1.10

- Issue on RangePicker
When scroll from 03/2021 to 04/2021, the calendar suddenly scroll to 05/2021, not show 04/2021
Press icon Previous Month in header, from 05/2021, the calendar cannot back to 04/2021
![report](https://user-images.githubusercontent.com/22596565/113087365-aaa37000-920d-11eb-8e91-9319694392ba.gif)

**Comment by metajet98** [comment]
At version 0.1.5 it's ok! I think the bug happen after that version

**Comment by seenewmax** [comment]
Came to see if somebody posted the issue. Same problem on DayPicker.single.

**Comment by seenewmax** [comment]
@MariaMelnik Thank you for your reply and thank you for this great package.
I checked the example and found the solution.

_firstDate = DateTime.now() causes the problem.
_firstDate = DateTime with "subtract(Duration(days: N))" works fine. (N must be at least 1)

If you put _firstDate = DateTime(2021, 3, 31) or DateTime.now().subtract(Duration(days: 0))
you will see it not working.

**Comment by MariaMelnik** [comment]
@seenewmax @metajet98 it is fixed in 0.2.4
Thank you for posting this issue!
