### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by sajadj313** [MariaMelnik/flutter_date_pickers#6]
I would be glad to see the localization feature for this extension.

**Comment by FoxPB** [comment]
there is already some way to change the name of the months to portuguese for example?

**Comment by MariaMelnik** [comment]
Hi,
this package use intl package for localization. So you can provide supported locales to you MaterialApp and everything should work.

To provide supported locales you can use flutter_localizations (it is [official way](https://flutter.dev/docs/development/accessibility-and-localization/internationalization))
To use it add to your project's pubspec.yaml 
```
dependencies:
  flutter_localizations:
    sdk: flutter
```

After it you can define delegates and locales in main widget:

```
import 'package:flutter_localizations/flutter_localizations.dart';

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: GlobalMaterialLocalizations.delegates,
         supportedLocales: [
           const Locale('en', 'US'), // American English
           const Locale('ru', 'RU'), // Russian
           const Locale("pt") // Portuguese
      ],

      // You can define default locale here if you wish
      // locale: Locale('en', 'US'),
    );
  }
}
```
If you device's locale is Portuguese you should see:
<img width="236" alt="Screenshot 2020-05-18 at 21 03 01" src="https://user-images.githubusercontent.com/20188655/82245219-33ddeb00-994b-11ea-9df3-e2fb4f31d8f1.png">


You can check example. I added support for this 3 locales to it.
Please, let me know if you have any questions here.
