### ISSUE TITLE
Ability to change the number of characters for the names of the week

### ISSUE THREAD

**Issue by RapegnoAndrea** [MariaMelnik/flutter_date_pickers#64]

**Comment by MariaMelnik** [comment]
@RapegnoAndrea could you please give more details?

**Comment by RapegnoAndrea** [comment]
@MariaMelnik yes of course, I was referring to the possibility of using for example "Mon" for Monday instead of "M" and so also for the other days

**Comment by MariaMelnik** [comment]
@RapegnoAndrea from version 0.2.5 you can set dayHeaderTitleBuilder to styles (`DatePickerStyles.dayHeaderTitleBuilder`) to customize titles.
You can check `day_picker_page.dart` in `example` to look at usage.

Don't forget update version in dependencies 
```
dependencies:
  flutter_date_pickers: ^0.2.5
```

Here is the day picker from example with customized weekday titles
<img width="319" alt="example" src="https://user-images.githubusercontent.com/20188655/136653242-57fedb62-c4ea-4683-8d6a-9e44c9c02592.png">
