### ISSUE TITLE
monthpicker not working

### ISSUE THREAD

**Issue by itsdani121** [MariaMelnik/flutter_date_pickers#66]
i want to select month but it give me error 

                   Widget buildWeekDatePicker(DateTime selectedDate, DateTime firstAllowedDate,
      DateTime lastAllowedDate, ValueChanged<DatePeriod> onNewSelected) {
    // add some colors to default settings
    DatePickerRangeStyles styles = DatePickerRangeStyles(
      selectedPeriodLastDecoration: BoxDecoration(
          color: Colors.red,
          borderRadius: BorderRadius.only(
              topRight: Radius.circular(10.0),
              bottomRight: Radius.circular(10.0))),
      selectedPeriodStartDecoration: BoxDecoration(
        color: Colors.green,
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(10.0), bottomLeft: Radius.circular(10.0)),
      ),
      selectedPeriodMiddleDecoration:
          BoxDecoration(color: Colors.yellow, shape: BoxShape.rectangle),
    );

    return MonthPicker(//here monthpicker is not a function error i dont know what can i do
        selectedDate: selectedDate,
        onChanged: onNewSelected,
        firstDate: firstAllowedDate,
        lastDate: lastAllowedDate,
        datePickerStyles: styles);
     }

**Comment by MariaMelnik** [comment]
@itsdani121 could you post error what you got?

**Comment by itsdani121** [comment]
> @itsdani121 could you post error what you got?

When i select monthpicker it sjow that it is not a function something like that pass a prefix bcz flutter material has also monthpicker which already deprecated something like that

**Comment by MariaMelnik** [comment]
Please, look at example: https://github.com/MariaMelnik/flutter_date_pickers/blob/master/example/lib/date_pickers_widgets/month_picker_page.dart

Flutter itself has MonthPicker class so you need to import month picker from this package with the prefix. Example: 
`import 'package:flutter_date_pickers/flutter_date_pickers.dart' as dp;`

and use like:
`dp.MonthPicker(...)`

**Comment by itsdani121** [comment]
What about othera who are attached as it is without as called

**Comment by MariaMelnik** [comment]
Check example please
