### ISSUE TITLE
Range picker ignores `displayedPeriodTitle` style

### ISSUE THREAD

**Issue by misha1024** [MariaMelnik/flutter_date_pickers#7]
No custom `displayedPeriodTitle` styling is applied on range picker.
Looks like issue is around `range_picker.dart` `line: 620`
```
child: ExcludeSemantics(
                child: Text(
                  localizations.formatMonthYear(displayedMonth),
                  key: selectedPeriodKey,
                  style: themeData.textTheme.subhead,
```

Replacing `style` with the following code should be enough
```
style: datePickerStyles?.displayedPeriodTitle ?? themeData.textTheme.subhead,
```

**Comment by MariaMelnik** [comment]
Thank you for report!
Will check and fix in next release.

**Comment by MariaMelnik** [comment]
Fixed in new release:
https://pub.dev/packages/flutter_date_pickers
