### ISSUE TITLE
Incorrect dates selected during Daylight Savings Time

### ISSUE THREAD

**Issue by stx** [MariaMelnik/flutter_date_pickers#79]
Thanks for your work on this excellent package.

Local device PST.

In the screenshot below, tapping March 14, 15, 16, 17, 18 or 19 incorrectly returns a DatePeriod starting a day early, from 2022-03-12 00:00:00.000 to 2022-03-19 23:59:59.999.

Tapping March 13 correctly returns 2022-03-13 00:00:00.000 - 2022-03-19 23:59:59.999.

![ss](https://user-images.githubusercontent.com/1284134/142744885-16360ad0-c328-4d2c-9394-cb54119775be.jpeg)

**Comment by MariaMelnik** [comment]
@stx thank you for posting this issue! It should be fixed in 0.2.7 version.

Feel free to reopen if something looks incorrect with new version as well.
