### ISSUE TITLE
Wishlist: allow providing custom style/decoration for each day

### ISSUE THREAD

**Issue by JustSayBien** [MariaMelnik/flutter_date_pickers#8]
For range-pickers it is possible atm to set `selectedPeriodStartDecoration`, `selectedPeriodMiddleDecoration` and `selectedPeriodLastDecoration`. 

It would be very nice to have more flexibility here and be able to decorate each day independently (for example via builder-pattern, like  `BoxDecoration Function(DateTime dateTime))`

**Comment by MariaMelnik** [comment]
@JustSayBien thank you for your feedback. I have this in my todo list for this package as well. Hope I will have time to implement it soon.

**Comment by MariaMelnik** [comment]
@JustSayBien Hi! Now you can decorate each day with `eventDecorationBuilder`.
https://pub.dev/packages/flutter_date_pickers

**Comment by cagricibuk** [comment]
How to make different styles for difrferent events

**Comment by MariaMelnik** [comment]
@cagricibuk you can use eventDecorationBuilder that is accessible for DayPicker, WeekPicker and RangePicker to do so.

Also you can read README file to find out what else you can customize in date pickers.
