### ISSUE TITLE
Add support for new Theme changes

### ISSUE THREAD

**Issue by kelegorm** [MariaMelnik/flutter_date_pickers#83]
`accentColor` and other stuff is deprecated in Flutter. Can you update app to get colors from new theme properties?

Instead `theme.accentColor` that could be `theme.colorScheme.secondary`.

You can read more about that [here](https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties#migration-guide).

Thank you!

**Comment by MariaMelnik** [comment]
@kelegorm thank you for posting this issue. It is fixed in version 0.2.8.

**Comment by MariaMelnik** [comment]
@kelegorm thank you for posting this issue. It is fixed in version 0.2.8.
