### ISSUE TITLE
First and last selected day style

### ISSUE THREAD

**Issue by RizaldiWiratama** [MariaMelnik/flutter_date_pickers#84]
hey @MariaMelnik thankyou for your answer in last issue, it works
but i want to implement something like this mockup for first and last selected day style
![image](https://user-images.githubusercontent.com/23089248/147425852-fd1fb6a1-217d-4b60-be95-c0f3e95a2b08.png)

my current implementation is like this 

```
dp.DatePickerRangeStyles dateRangeStyles = dp.DatePickerRangeStyles(
  selectedPeriodLastDecoration: BoxDecoration(
    color: Color.fromRGBO(253, 85, 10, 1),
    borderRadius: BorderRadiusDirectional.only(
        topEnd: Radius.circular(32.0),
        bottomEnd: Radius.circular(32.0)),
  ),
  selectedPeriodStartDecoration: BoxDecoration(
    color: Color.fromRGBO(253, 85, 10, 1),
    borderRadius: BorderRadiusDirectional.only(
        topStart: Radius.circular(32.0),
        bottomStart: Radius.circular(32.0)),
  ),
  ...
);
```
result : 
![image](https://user-images.githubusercontent.com/23089248/147425948-89a7f59f-ac3c-4cbd-8980-c7e83cdc34fe.png)

can i implement something like that mockup? 
i try with BoxShape.circle or using border with opacity black 
```
dp.DatePickerRangeStyles dateRangeStyles = dp.DatePickerRangeStyles(
  selectedPeriodLastDecoration: BoxDecoration(
    color: Color.fromRGBO(253, 85, 10, 1),
    borderRadius: BorderRadius.only(
        topRight: Radius.circular(32.0),
        bottomRight: Radius.circular(32.0)),
    border: Border.all(color: Colors.black.withOpacity(0.1), width: 4),
  ),
  selectedPeriodStartDecoration: BoxDecoration(
    color: Color.fromRGBO(253, 85, 10, 1),
    border: Border.all(color: Color.fromRGBO(253, 85, 10, 0.1), width: 4),
    shape: BoxShape.circle
  ),
  ...
);
```

but the result will be like this 
![image](https://user-images.githubusercontent.com/23089248/147426415-5160ef51-4fc3-451b-a993-7a66b4514c05.png)

Hope to see any workaround to achieve that mockup, thankyouu

**Comment by MariaMelnik** [comment]
@RizaldiWiratama you can try idea that was described here: https://github.com/MariaMelnik/flutter_date_pickers/issues/49

**Comment by RizaldiWiratama** [comment]
thanks @MariaMelnik i will try it :)

**Comment by RizaldiWiratama** [comment]
thankyou @MariaMelnik it works !
