### ISSUE TITLE
month is not disabled

### ISSUE THREAD

**Issue by marinkobabic** [MariaMelnik/flutter_date_pickers#87]
if the month is started with 

firstDate: 2021-01-11 00:00:00.000
lastDate: 2022-01-11 23:59:59.999

then February 2022 is not disabled, but it should be

https://github.com/MariaMelnik/flutter_date_pickers/blob/master/lib/src/i_selectable_picker.dart#L610 

by removing + 1 in the line above all works fine

**Comment by MariaMelnik** [comment]
@marinkobabic thank you for posting this issue.
It should be fixed in version 0.2.8.

Don't hesitate to reopen issue if something is wrong in new version as well.
