### ISSUE TITLE
Inheritance Suggestion

### ISSUE THREAD

**Issue by MarceloRab** [MariaMelnik/flutter_date_pickers#9]
Could you leave a generic method for DatePeriod?

I wish I could do that.

```
class MyDatePeriodic extends DatePeriod {
  MyDatePeriodic(DateTime start, DateTime end) : super(start, end);

  int _numDiasPeriodo() {
    return this.start.difference(end).inDays;
  }

  List<String> consultaDiaListIds() {
    return List.generate(_numDiasPeriodo(), (index) {
      DateTime dateTime = start.add(Duration(days: index));
      return MyDateHelper.getIdAgendaFireString(dateTime);
    });
  }
}
```

**Comment by MariaMelnik** [comment]
@MarceloRab I think you don't need to extend DatePeriod class to get custom string for every day from it.
You can handle this in outside DatePeriod in class where you need to generate such kind of strings.

I am closing this issue. If you think I don't understand you correct and it is useful feature please reopen it and provide little bit more information why it should be done this way.
