### ISSUE TITLE
Make this package compatible with Flutter 3.0.0

### ISSUE THREAD

**Issue by th0rgall** [MariaMelnik/flutter_date_pickers#93]
This line causes a build warning: 
https://github.com/MariaMelnik/flutter_date_pickers/blob/e973c7d6b88b645413958a7f718e7d51fa26639d/lib/src/day_based_changable_picker.dart#L318

See the release notes for a suggested fix: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings

**Comment by MariaMelnik** [comment]
@th0rgall thank you for posting it! Will update soon.

**Comment by MariaMelnik** [comment]
@th0rgall you can now use 0.3.1 version to avoid warning.
 I am closing issue but feel free to reopen it if something is incorrect.

**Comment by th0rgall** [comment]
Thank you!
